version: '3.9'

services:
  server:
    build:
      context: .
    container_name: go_thumb_processor_worker
    restart: always
    ports:
      - "8082:8080"
    networks:
      - hackathon-network
networks:
  hackathon-network:
    driver: bridge
