basePath: /
host: localhost:8080
info:
  contact: {}
  description: Hackathon
  title: Thumb processor worker
  version: 0.1.0
paths:
  /health:
    get:
      description: Checks the health status of the application.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Health Check
      tags:
      - Health Check
swagger: "2.0"
